### ISSUE TITLE
Flintc can't compile the SimpleAuction.flint example

### ISSUE THREAD

**Issue by seusher** [franklinsch/flint#181]
Run:

```
docker pull franklinsch/flint  
docker run -i -t franklinsch/flint
flintc /flint/examples/solidity-translation/SimpleAuction.flint 
```

You will then get an error:
```
root@270bc8b8ac4e:/# flintc /flint/examples/solidity-translation/SimpleAuction.flint 
Error in SimpleAuction.flint:
Expected token } at line 23, column 3:
  @payable
  ^^^^^^^^
```

I haven't dug into it, but it looks like the parser does properly parse the @payable attribute, but a parse error causes it to reset the index into the token list, so it processes "@payable" again where it would have found a '}' token had the position not been rolled back.

**Comment by franklinsch** [comment]
Hi Sean, thanks for your interest in Flint! The contracts in `examples/solidity-translation` require features which aren’t supported by the latest version of `flintc` yet.

Please refer to `examples/valid` for Flint programs which should compile with the latest version of the compiler.

**Comment by franklinsch** [comment]
SimpleAuction.flint can now be compiled, with #217.
